import { useState } from "react";
import { Camera, CheckCircle2, FileSignature, MapPin, ShieldAlert, Upload } from "lucide-react";
import { toast } from "sonner";
import { Button, EntityForm, Modal, PageHeader, StatCard, StatusBadge } from "@/components/ui";

export function RatesPage() {
  const [open, setOpen] = useState(false);
  const rules = [
    ["Van de carga", "RD$ 650 · 38/km · 6/min", "Santo Domingo", "Activa"], ["Camión pequeño", "RD$ 950 · 52/km · 8/min", "Gran SD", "Activa"],
    ["Furgón 53'", "RD$ 2,400 · 76/km · 12/min", "Nacional", "Activa"], ["Reserva 24h", "+12% cargo programado", "Todas", "Revisión"],
  ];
  const fields = [{ name: "nombre", label: "Nombre de tarifa" }, { name: "zona", label: "Zona" }, { name: "vehiculo", label: "Categoría de vehículo" }, { name: "base", label: "Precio base", type: "number" as const }, { name: "km", label: "Precio por km", type: "number" as const }, { name: "minuto", label: "Precio por minuto", type: "number" as const }, { name: "recargos", label: "Recargos y horario", type: "textarea" as const }];
  return <div><PageHeader title="Tarifas" subtitle="Reglas de precio por zona, vehículo y horario" action="Crear tarifa" onAction={() => setOpen(true)} />
    <section className="stats-grid"><StatCard stat={{ label: "Tarifas activas", value: "18", helper: "3 rate cards", tone: "blue" }} /><StatCard stat={{ label: "Recargos", value: "7", helper: "2 por horario pico", tone: "orange" }} /><StatCard stat={{ label: "Promedio / km", value: "RD$ 42", helper: "+3.2% este mes", tone: "green" }} /><StatCard stat={{ label: "Cambios hoy", value: "3", helper: "Todos auditados", tone: "slate" }} /></section>
    <section className="rate-layout"><article className="panel"><div className="panel-heading"><div><h2>Matriz de tarifas</h2><p>Rate cards y reglas vigentes</p></div><div className="segmented"><button className="active">Reglas</button><button>Zonas</button><button>Recargos</button></div></div><div className="rate-table"><div className="rate-row rate-head"><span>Vehículo</span><span>Base / km / min</span><span>Zona</span><span>Estado</span></div>{rules.map((rule) => <button className="rate-row" key={rule[0]}><strong>{rule[0]}</strong><span>{rule[1]}</span><span>{rule[2]}</span><StatusBadge>{rule[3]}</StatusBadge></button>)}</div></article><aside className="dark-insight"><span>Regla seleccionada</span><h3>Camión pequeño · horario pico</h3><p>Se aplica +18% entre 16:00–19:00. El peaje se transfiere al cliente y la espera se factura tras 10 min.</p><div><span>Tarifa mínima</span><strong>RD$ 950</strong></div><div><span>Ayudante</span><strong>RD$ 450</strong></div><div><span>Espera</span><strong>RD$ 8/min</strong></div><StatusBadge>Pendiente aprobación</StatusBadge></aside></section>
    <Modal open={open} onClose={() => setOpen(false)} title="Crear tarifa" description="Define la regla base, cobertura y recargos." wide><EntityForm fields={fields} onCancel={() => setOpen(false)} onSubmit={() => { toast.success("Tarifa enviada a aprobación"); setOpen(false); }} /></Modal></div>;
}

const incidents = [
  { id: "ORD-000132", title: "Retraso por tráfico", meta: "Asignar operador", status: "Crítica", sla: "18 min" },
  { id: "ORD-000140", title: "Cliente no responde", meta: "Juan Pérez", status: "Media", sla: "42 min" },
  { id: "ORD-000151", title: "Carga incompleta", meta: "Asignar operador", status: "Alta", sla: "1 h 08" },
  { id: "ORD-000155", title: "GPS inestable", meta: "Carlos Díaz", status: "Baja", sla: "2 h 14" },
];

export function IncidentsPage() {
  const [selected, setSelected] = useState(incidents[0]); const [open, setOpen] = useState(false);
  const fields = [{ name: "orden", label: "Orden" }, { name: "tipo", label: "Tipo", type: "select" as const, options: ["Retraso", "Daño", "Cliente ausente", "Dirección incorrecta", "Problema del vehículo", "Otro"] }, { name: "severidad", label: "Severidad", type: "select" as const, options: ["Baja", "Media", "Alta", "Crítica"] }, { name: "responsable", label: "Responsable" }, { name: "descripcion", label: "Descripción", type: "textarea" as const }];
  return <div><PageHeader title="Incidencias" subtitle="Clasificación, SLA y resolución operativa" action="Reportar incidencia" onAction={() => setOpen(true)} /><section className="stats-grid"><StatCard stat={{ label: "Abiertas", value: "9", helper: "4 nuevas hoy", tone: "orange" }} /><StatCard stat={{ label: "Críticas", value: "2", helper: "Atención inmediata", tone: "red" }} /><StatCard stat={{ label: "SLA vencido", value: "1", helper: "Escalada a gerencia", tone: "red" }} /><StatCard stat={{ label: "Resueltas hoy", value: "14", helper: "Promedio 36 min", tone: "green" }} /></section>
    <section className="incident-layout"><article className="panel incident-queue"><div className="panel-heading"><div><h2>Cola priorizada</h2><p>Ordenada por severidad y tiempo restante</p></div></div>{incidents.map((incident) => <button className={selected.id === incident.id ? "selected" : ""} key={incident.id} onClick={() => setSelected(incident)}><ShieldAlert size={18} /><span><strong>{incident.id}</strong><small>{incident.title} · {incident.meta}</small></span><em>SLA {incident.sla}</em><StatusBadge>{incident.status}</StatusBadge></button>)}</article><article className="panel incident-detail"><div className="panel-heading"><div><span className="eyebrow">Detalle</span><h2>{selected.id}</h2></div><StatusBadge>{selected.status}</StatusBadge></div><h3>{selected.title}</h3><p>Ruta: Herrera → Boca Chica<br />Conductor: Carlos Díaz<br />SLA restante: {selected.sla}</p><div className="timeline"><div><i /><span><strong>Incidencia reportada</strong><small>11:05 · Carlos Díaz</small></span></div><div><i /><span><strong>Operador notificado</strong><small>11:06 · Sistema</small></span></div><div className="pending"><i /><span><strong>Esperando resolución</strong><small>Adjunta comentario o evidencia</small></span></div></div><textarea placeholder="Agregar comentario interno..." /><div className="incident-actions"><Button variant="danger">Escalar</Button><Button onClick={() => toast.success("Incidencia resuelta")}>Resolver</Button></div></article></section>
    <Modal open={open} onClose={() => setOpen(false)} title="Reportar incidencia" description="Registra severidad, ubicación y responsable." wide><EntityForm fields={fields} onCancel={() => setOpen(false)} onSubmit={() => { toast.success("Incidencia reportada y SLA iniciado"); setOpen(false); }} /></Modal></div>;
}

const proofs = [
  ["ORD-000124", "Foto + GPS validado", "Aprobada", Camera], ["ORD-000125", "Firma pendiente", "Pendiente", FileSignature], ["ORD-000126", "Foto + GPS validado", "Aprobada", Camera],
  ["ORD-000127", "Firma pendiente", "Pendiente", FileSignature], ["ORD-000128", "Foto + GPS validado", "Aprobada", Camera], ["ORD-000129", "Firma pendiente", "Pendiente", FileSignature],
];

export function EvidencePage() {
  const [open, setOpen] = useState(false);
  const fields = [{ name: "orden", label: "Orden" }, { name: "receptor", label: "Nombre del receptor" }, { name: "documento", label: "Documento del receptor" }, { name: "hora", label: "Fecha y hora", type: "date" as const }, { name: "coordenadas", label: "Coordenadas GPS" }, { name: "comentario", label: "Comentario", type: "textarea" as const }];
  return <div><PageHeader title="Evidencias" subtitle="Fotos, firmas y coordenadas de entrega" action="Subir evidencia" onAction={() => setOpen(true)} /><section className="stats-grid"><StatCard stat={{ label: "Por revisar", value: "21", helper: "3 críticas", tone: "orange" }} /><StatCard stat={{ label: "Aprobadas", value: "88", helper: "Hoy", tone: "green" }} /><StatCard stat={{ label: "Rechazadas", value: "4", helper: "Imagen ilegible", tone: "red" }} /><StatCard stat={{ label: "Sin firma", value: "6", helper: "Requieren contacto", tone: "slate" }} /></section>
    <section className="panel evidence-board"><div className="panel-heading"><div><h2>Bandeja de revisión</h2><p>Validación visual y automática</p></div><div className="segmented"><button className="active">Galería</button><button>Tabla</button></div></div><div className="proof-grid">{proofs.map(([id, label, status, Icon]) => <button key={String(id)}><div className="proof-preview"><Icon size={30} /><span className="gps-chip"><MapPin size={12} /> SDQ</span></div><span><strong>{String(id)}</strong><small>{String(label)}</small></span><StatusBadge>{String(status)}</StatusBadge></button>)}</div></section><section className="validation-banner"><CheckCircle2 size={24} /><div><strong>Validación automática activa</strong><p>Coordenadas, hora de entrega, firma y foto se cruzan contra la orden antes de facturar.</p></div><span>96.8% precisión</span></section>
    <Modal open={open} onClose={() => setOpen(false)} title="Subir evidencias" description="Añade archivos, firma y ubicación de entrega." wide><div className="upload-zone"><Upload size={24} /><strong>Arrastra fotos o documentos</strong><span>JPG, PNG o PDF · máximo 10 MB</span></div><EntityForm fields={fields} onCancel={() => setOpen(false)} onSubmit={() => { toast.success("Evidencia cargada para validación"); setOpen(false); }} /></Modal></div>;
}
